### ISSUE TITLE
Failed to extend rule defined in utillities.scss

### ISSUE THREAD

**Issue by Jancat** [milad-alizadeh/vue-cli-plugin-scss-base#2]
Hey, I coming again 😀.

The rule defined in utillities.scss(like .u-visually-hidden) failed to be extended in component scss.

```scss
<style lang="scss" module>
.item {
  .label {
    @extend .u-visually-hidden;
  }
}
</style>
```

The error:
```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

  }
           ^
      ".item .label" failed to @extend ".u-visually-hidden".
The selector ".u-visually-hidden" was not found.
Use "@extend .u-visually-hidden !optional" if the extend should be able to fail.
      in xxx.vue
```

But it can be used as inline class
```html
<template>
    <!-- ok -->
    <div class="u-visually-hidden"></div>
<template>
```

**Comment by milad-alizadeh** [comment]
The reason for this is because the `utilities` classes are not imported on each individual component and is only imported to `App.vue` as part `base.scss`. In these cases you have two options.
1 - Import the utility file you want to use directly in your component
```
<template/>
  <div class="example-component">This text is still visible to screen readers</div>
<template/>

<style>
@import '@/scss/utilities/_u-visually-hidden.scss';
.example-component {
   @extend .u-visually-hidden;
}
</style>
```

2 - You can directly include the class in your component's HTML. 

```
<template/>
  <div class="example-component u-visually-hidden">This text is still visible to screen readers</div>
<template/>
```

The latter option is recommended since you don't have to import the utility file and it's less verbose. Also as a rule of thumb using `@extend` is not recommended. Here is a [detailed article](https://www.sitepoint.com/avoid-sass-extend/) about this.

**Comment by Jancat** [comment]
@milad-alizadeh Thanks for your help again! I will choose the latter option.
